import type { Meta, StoryObj } from '@storybook/react-vite';
import {
  Canvas,
  Controls,
  Heading,
  Stories,
  Subtitle,
  Title,
} from '@storybook/addon-docs/blocks';
import { TabNavigation } from './Tabs';

const horizontalItems = [
  {
    value: 'overview',
    label: 'Overview',
    content: 'Overview content for the selected tab.',
  },
  {
    value: 'tokens',
    label: 'Tokens',
    counter: '24',
    content: 'Token documentation and implementation notes.',
  },
  {
    value: 'patterns',
    label: 'Patterns',
    iconAfter: 'arrowRight',
    content: 'Patterns, responsive behavior, and composition guidance.',
  },
] as const;

const verticalItems = [
  {
    value: 'overview',
    label: 'Overview',
    iconBefore: 'search',
  },
  {
    value: 'tokens',
    label: 'Tokens',
    counter: '17',
  },
  {
    value: 'patterns',
    label: 'Patterns',
    iconAfter: 'arrowRight',
  },
  {
    value: 'guidelines',
    label: 'Guidelines',
  },
  {
    value: 'release-notes',
    label: 'Release Notes',
  },
] as const;

const meta = {
  title: 'Components/Tab Navigation',
  component: TabNavigation,
  tags: ['autodocs'],
  args: {
    items: horizontalItems,
    size: 'md',
    fullWidth: false,
    orientation: 'horizontal',
  },
  argTypes: {
    items: {
      control: false,
      description:
        'Collection of tabs composed from label, optional icon slots, optional counter, and optional panel content.',
    },
    onValueChange: {
      control: false,
    },
  },
  parameters: {
    docs: {
      page: () => (
        <>
          <Title />
          <Subtitle>
            Organism-level tab navigation composed from `Tab base`, `Tab states`, `Icon`, and
            `Counter` building blocks from Figma.
          </Subtitle>
          <p>
            This component currently exposes the two published layouts from Figma: horizontal
            and vertical. Use the story canvases below to review the implementation without the
            autogenerated docs renderer tripping over the complex `items` prop shape.
          </p>
          <Heading>Horizontal</Heading>
          <Canvas of={Horizontal} />
          <Heading>Vertical</Heading>
          <Canvas of={Vertical} />
          <Heading>API</Heading>
          <Controls />
          <Stories includePrimary={false} />
        </>
      ),
    },
  },
} satisfies Meta<typeof TabNavigation>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Playground: Story = {};

export const Horizontal: Story = {
  args: {
    items: horizontalItems,
    orientation: 'horizontal',
  },
  parameters: {
    layout: 'padded',
  },
};

export const Vertical: Story = {
  args: {
    items: verticalItems,
    orientation: 'vertical',
    fullWidth: true,
    showPanel: false,
  },
  parameters: {
    layout: 'padded',
  },
};

export const Compact: Story = {
  args: {
    size: 'sm',
  },
};
