import tabComponentColors from './figma/component_tab_color.json';
import tabComponentSizing from './figma/component_tab_size.json';
import focusComponentColors from './figma/component_focus_color.json';
import focusComponentSizing from './figma/component_focus_size.json';
import counterComponentColors from './figma/component_counter_color.json';
import counterComponentSizing from './figma/component_counter_size.json';
import linkRegularComponentColors from './figma/component_link_color_regular.json';
import linkInverseComponentColors from './figma/component_link_color_inverse.json';
import linkComponentSizing from './figma/component_link_size.json';
import { getTokenReference } from './helpers';

export const componentTokens = {
  tab: {
    borderColor: getTokenReference(tabComponentColors, ['tab', 'border', 'color']),
    borderColorHover: getTokenReference(tabComponentColors, ['tab', 'border', 'color-hover']),
    borderColorPressed: getTokenReference(tabComponentColors, ['tab', 'border', 'color-pressed']),
    borderColorActive: getTokenReference(tabComponentColors, ['tab', 'border', 'color-active']),
    borderColorDisabled: getTokenReference(tabComponentColors, ['tab', 'border', 'color-disabled']),
    fillColor: getTokenReference(tabComponentColors, ['tab', 'fill', 'color']),
    fillColorHover: getTokenReference(tabComponentColors, ['tab', 'fill', 'color-hover']),
    fillColorPressed: getTokenReference(tabComponentColors, ['tab', 'fill', 'color-pressed']),
    fillColorActive: getTokenReference(tabComponentColors, ['tab', 'fill', 'color-active']),
    fillColorDisabled: getTokenReference(tabComponentColors, ['tab', 'fill', 'color-disabled']),
    iconColor: getTokenReference(tabComponentColors, ['tab', 'icon', 'color']),
    iconColorHover: getTokenReference(tabComponentColors, ['tab', 'icon', 'color-hover']),
    iconColorPressed: getTokenReference(tabComponentColors, ['tab', 'icon', 'color-pressed']),
    iconColorActive: getTokenReference(tabComponentColors, ['tab', 'icon', 'color-active']),
    iconColorDisabled: getTokenReference(tabComponentColors, ['tab', 'icon', 'color-disabled']),
    textColor: getTokenReference(tabComponentColors, ['tab', 'text', 'color']),
    textColorHover: getTokenReference(tabComponentColors, ['tab', 'text', 'color-hover']),
    textColorPressed: getTokenReference(tabComponentColors, ['tab', 'text', 'color-pressed']),
    textColorActive: getTokenReference(tabComponentColors, ['tab', 'text', 'color-active']),
    textColorDisabled: getTokenReference(tabComponentColors, ['tab', 'text', 'color-disabled']),
    borderWidthBase: getTokenReference(tabComponentSizing, ['tab', 'border-width']),
    borderWidthInactive: getTokenReference(tabComponentSizing, ['tab', 'border-width-inactive']),
    borderWidthActive: getTokenReference(tabComponentSizing, ['tab', 'border-width-active']),
    cornerRadius: getTokenReference(tabComponentSizing, ['tab', 'corner-radius']),
    gap: getTokenReference(tabComponentSizing, ['tab', 'gap']),
    paddingX: getTokenReference(tabComponentSizing, ['tab', 'padding-x']),
    paddingY: getTokenReference(tabComponentSizing, ['tab', 'padding-y']),
  },
  focus: {
    borderColor: getTokenReference(focusComponentColors, ['focus', 'border', 'color']),
    borderWidth: getTokenReference(focusComponentSizing, ['focus', 'border-width']),
    cornerRadius: getTokenReference(focusComponentSizing, ['focus', 'corner-radius']),
    paddingX: getTokenReference(focusComponentSizing, ['focus', 'padding-x']),
    paddingY: getTokenReference(focusComponentSizing, ['focus', 'padding-y']),
  },
  counter: {
    borderColor: getTokenReference(counterComponentColors, ['counter', 'border', 'color']),
    borderColorActive: getTokenReference(counterComponentColors, ['counter', 'border', 'color-active']),
    fillColor: getTokenReference(counterComponentColors, ['counter', 'fill', 'color']),
    fillColorActive: getTokenReference(counterComponentColors, ['counter', 'fill', 'color-active']),
    textColor: getTokenReference(counterComponentColors, ['counter', 'text', 'color']),
    textColorActive: getTokenReference(counterComponentColors, ['counter', 'text', 'color-active']),
    borderWidth: getTokenReference(counterComponentSizing, ['counter', 'border-width']),
    cornerRadius: getTokenReference(counterComponentSizing, ['counter', 'corner-radius']),
    maxWidth: getTokenReference(counterComponentSizing, ['counter', 'max-width']),
    paddingX: getTokenReference(counterComponentSizing, ['counter', 'padding-x']),
    size: getTokenReference(counterComponentSizing, ['counter', 'size']),
  },
  link: {
    size: {
      gap: getTokenReference(linkComponentSizing, ['link', 'gap']),
      iconSize: getTokenReference(linkComponentSizing, ['link', 'icon-size']),
      paddingX: getTokenReference(linkComponentSizing, ['link', 'padding-x']),
      paddingY: getTokenReference(linkComponentSizing, ['link', 'padding-y']),
    },
    regular: {
      fillColor: getTokenReference(linkRegularComponentColors, ['link', 'fill', 'color']),
      fillColorHover: getTokenReference(linkRegularComponentColors, ['link', 'fill', 'color-hover']),
      fillColorPressed: getTokenReference(linkRegularComponentColors, ['link', 'fill', 'color-pressed']),
      fillColorSelected: getTokenReference(linkRegularComponentColors, ['link', 'fill', 'color-selected']),
      fillColorDisabled: getTokenReference(linkRegularComponentColors, ['link', 'fill', 'color-disabled']),
      fillColorVisited: getTokenReference(linkRegularComponentColors, ['link', 'fill', 'color-visited']),
      iconColor: getTokenReference(linkRegularComponentColors, ['link', 'icon', 'color']),
      iconColorHover: getTokenReference(linkRegularComponentColors, ['link', 'icon', 'color-hover']),
      iconColorPressed: getTokenReference(linkRegularComponentColors, ['link', 'icon', 'color-pressed']),
      iconColorSelected: getTokenReference(linkRegularComponentColors, ['link', 'icon', 'color-selected']),
      iconColorDisabled: getTokenReference(linkRegularComponentColors, ['link', 'icon', 'color-disabled']),
      iconColorVisited: getTokenReference(linkRegularComponentColors, ['link', 'icon', 'color-visited']),
      textColor: getTokenReference(linkRegularComponentColors, ['link', 'text', 'color']),
      textColorHover: getTokenReference(linkRegularComponentColors, ['link', 'text', 'color-hover']),
      textColorPressed: getTokenReference(linkRegularComponentColors, ['link', 'text', 'color-pressed']),
      textColorSelected: getTokenReference(linkRegularComponentColors, ['link', 'text', 'color-selected']),
      textColorDisabled: getTokenReference(linkRegularComponentColors, ['link', 'text', 'color-disabled']),
      textColorVisited: getTokenReference(linkRegularComponentColors, ['link', 'text', 'color-visited']),
    },
    inverse: {
      fillColor: getTokenReference(linkInverseComponentColors, ['link', 'fill', 'color']),
      fillColorHover: getTokenReference(linkInverseComponentColors, ['link', 'fill', 'color-hover']),
      fillColorPressed: getTokenReference(linkInverseComponentColors, ['link', 'fill', 'color-pressed']),
      fillColorSelected: getTokenReference(linkInverseComponentColors, ['link', 'fill', 'color-selected']),
      fillColorDisabled: getTokenReference(linkInverseComponentColors, ['link', 'fill', 'color-disabled']),
      fillColorVisited: getTokenReference(linkInverseComponentColors, ['link', 'fill', 'color-visited']),
      iconColor: getTokenReference(linkInverseComponentColors, ['link', 'icon', 'color']),
      iconColorHover: getTokenReference(linkInverseComponentColors, ['link', 'icon', 'color-hover']),
      iconColorPressed: getTokenReference(linkInverseComponentColors, ['link', 'icon', 'color-pressed']),
      iconColorSelected: getTokenReference(linkInverseComponentColors, ['link', 'icon', 'color-selected']),
      iconColorDisabled: getTokenReference(linkInverseComponentColors, ['link', 'icon', 'color-disabled']),
      iconColorVisited: getTokenReference(linkInverseComponentColors, ['link', 'icon', 'color-visited']),
      textColor: getTokenReference(linkInverseComponentColors, ['link', 'text', 'color']),
      textColorHover: getTokenReference(linkInverseComponentColors, ['link', 'text', 'color-hover']),
      textColorPressed: getTokenReference(linkInverseComponentColors, ['link', 'text', 'color-pressed']),
      textColorSelected: getTokenReference(linkInverseComponentColors, ['link', 'text', 'color-selected']),
      textColorDisabled: getTokenReference(linkInverseComponentColors, ['link', 'text', 'color-disabled']),
      textColorVisited: getTokenReference(linkInverseComponentColors, ['link', 'text', 'color-visited']),
    },
  },
} as const;
